use MX_DWH
go

if object_id('dbo.VW_ODS_DN_RESULTADO_NOMINA', 'V') is not null
	drop view dbo.VW_ODS_DN_RESULTADO_NOMINA
Go

create view dbo.VW_ODS_DN_RESULTADO_NOMINA AS
SELECT N.ID_PROCESO,N.NRO_EMPLEADO,E.NOMBRE_EMPLEADO,E.PATERNO_EMPLEADO,E.MATERNO_EMPLEADO
,E.CANT_DIAS,E.SALARIO_MINIMO,E.TOTAL_PERCEPCION,E.MINIMO_GARANTIZADO,E.DEDUC_TOTAL,E.DEDUC_APLICADAS,E.DEDUC_PENDIENTES,E.NUEVO_NETO
,N.NRO_NOMINA_PROCESO,N.TIPO_DEDUCCION,N.ORDEN,N.CARACTERISTICA,N.CONCEPTO,N.DESC_CONCEPTO,N.IMPORTE,N.DESCUENTO,N.NUEVO_NETO AS NUEVO_NETO_DEDUC
,P.NUM_CIA,C.COMPAÑIA,C.SALARIO_MINIMO AS SALARIO_MINIMO_CIA
,P.NRO_PROCESO,P.TIPO_PROCESO,P.PER_PROCESO,P.AÑO_PROCESO,P.SEM_PROCESO,P.MES_PROCESO,P.ESTADO
FROM dbo.ODS_DN_NOMINA_DEDUCCION AS N
INNER JOIN ODS_DN_NOMINA_PROCESO AS E on N.ID_PROCESO = E.ID_PROCESO AND N.NRO_NOMINA_PROCESO = E.NRO_NOMINA_PROCESO AND N.NRO_EMPLEADO = E.NRO_EMPLEADO
INNER JOIN ODS_DN_PROCESO AS P ON E.ID_PROCESO = P.ID
INNER JOIN VW_ODS_DN_COMPAÑIA AS C ON P.NUM_CIA = C.NUM_CIA
GO